import TablePagination, { TablePaginationProps } from "./TablePagination";
import { Meta, StoryFn } from "@storybook/react";

export default {
  title: "Components/ui/TablePagination",
  component: TablePagination,
  tags: ["autodocs"],
} as Meta;

const tableData = [
  {
    id: 1,
    Name: "Tiger Nixon",
    Position: "System Architect",
    Office: "Edinburgh",
    Age: 61,
    StartDate: "2011-04-25",
    Salary: "320800",
  },
  {
    id: 2,
    Name: "Garrett Winters",
    Position: "Accountant",
    Office: "Tokyo",
    Age: 63,
    StartDate: "2011-07-25",
    Salary: "170750",
  },
  {
    id: 3,
    Name: "Ashton Cox",
    Position: "Junior Technical Author",
    Office: "San Francisco",
    Age: 66,
    StartDate: "2009-01-12",
    Salary: "86000",
  },
  {
    id: 4,
    Name: "Cedric Kelly",
    Position: "Senior Javascript Developer",
    Office: "Edinburgh",
    Age: 22,
    StartDate: "2012-03-29",
    Salary: "433060",
  },
  {
    id: 5,
    Name: "Airi Satou",
    Position: "Accountant",
    Office: "Tokyo",
    Age: 33,
    StartDate: "2008-11-28",
    Salary: "162700",
  },
  {
    id: 6,
    Name: "Brielle Williamson",
    Position: "Integration Specialist",
    Office: "New York",
    Age: 61,
    StartDate: "2012-12-02",
    Salary: "372000",
  },
  {
    id: 7,
    Name: "Herrod Chandler",
    Position: "Sales Assistant",
    Office: "San Francisco",
    Age: 59,
    StartDate: "2012-08-06",
    Salary: "137500",
  },
  {
    id: 8,
    Name: "Rhona Davidson",
    Position: "Integration Specialist",
    Office: "Tokyo",
    Age: 55,
    StartDate: "2010-10-14",
    Salary: "327900",
  },
  {
    id: 9,
    Name: "Colleen Hurst",
    Position: "Javascript Developer",
    Office: "San Francisco",
    Age: 39,
    StartDate: "2009-09-15",
    Salary: "205500",
  },
  {
    id: 10,
    Name: "Sonya Frost",
    Position: "Software Engineer",
    Office: "Edinburgh",
    Age: 23,
    StartDate: "2008-12-13",
    Salary: "103600",
  },
  {
    id: 11,
    Name: "Jena Gaines",
    Position: "Office Manager",
    Office: "London",
    Age: 30,
    StartDate: "2008-12-19",
    Salary: "90560",
  },
  {
    id: 12,
    Name: "Quinn Flynn",
    Position: "Support Lead",
    Office: "Edinburgh",
    Age: 22,
    StartDate: "2013-03-03",
    Salary: "342000",
  },
  {
    id: 13,
    Name: "Charde Marshall",
    Position: "Regional Director",
    Office: "San Francisco",
    Age: 36,
    StartDate: "2008-10-16",
    Salary: "470600",
  },
  {
    id: 14,
    Name: "Haley Kennedy",
    Position: "Senior Marketing Designer",
    Office: "London",
    Age: 43,
    StartDate: "2012-12-18",
    Salary: "313500",
  },
  {
    id: 15,
    Name: "Tatyana Fitzpatrick",
    Position: "Regional Director",
    Office: "London",
    Age: 19,
    StartDate: "2010-03-17",
    Salary: "385750",
  },
  {
    id: 16,
    Name: "Michael Silva",
    Position: "Marketing Designer",
    Office: "London",
    Age: 66,
    StartDate: "2012-11-27",
    Salary: "198500",
  },
  {
    id: 17,
    Name: "Paul Byrd",
    Position: "Chief Financial Officer (CFO)",
    Office: "New York",
    Age: 64,
    StartDate: "2010-06-09",
    Salary: "725000",
  },
  {
    id: 18,
    Name: "Gloria Little",
    Position: "Systems Administrator",
    Office: "New York",
    Age: 59,
    StartDate: "2009-04-10",
    Salary: "237500",
  },
  {
    id: 19,
    Name: "Bradley Greer",
    Position: "Software Engineer",
    Office: "London",
    Age: 41,
    StartDate: "2012-10-13",
    Salary: "132000",
  },
  {
    id: 20,
    Name: "Dai Rios",
    Position: "Personnel Lead",
    Office: "Edinburgh",
    Age: 35,
    StartDate: "2012-09-26",
    Salary: "217500",
  },
  {
    id: 21,
    Name: "Jenette Caldwell",
    Position: "Development Lead",
    Office: "New York",
    Age: 30,
    StartDate: "2011-09-03",
    Salary: "345000",
  },
  {
    id: 22,
    Name: "Yuri Berry",
    Position: "Chief Marketing Officer (CMO)",
    Office: "New York",
    Age: 40,
    StartDate: "2009-06-25",
    Salary: "675000",
  },
  {
    id: 23,
    Name: "Caesar Vance",
    Position: "Pre-Sales Support",
    Office: "New York",
    Age: 21,
    StartDate: "2011-12-12",
    Salary: "106450",
  },
  {
    id: 24,
    Name: "Doris Wilder",
    Position: "Sales Assistant",
    Office: "Sydney",
    Age: 23,
    StartDate: "2010-09-20",
    Salary: "85600",
  },
  {
    id: 25,
    Name: "Angelica Ramos",
    Position: "Chief Executive Officer (CEO)",
    Office: "London",
    Age: 47,
    StartDate: "2009-10-09",
    Salary: "1200000",
  },
  {
    id: 26,
    Name: "Gavin Joyce",
    Position: "Developer",
    Office: "Edinburgh",
    Age: 42,
    StartDate: "2010-12-22",
    Salary: "92575",
  },
  {
    id: 27,
    Name: "Jennifer Chang",
    Position: "Regional Director",
    Office: "Singapore",
    Age: 28,
    StartDate: "2010-11-14",
    Salary: "357650",
  },
  {
    id: 28,
    Name: "Brenden Wagner",
    Position: "Software Engineer",
    Office: "San Francisco",
    Age: 28,
    StartDate: "2011-06-07",
    Salary: "206850",
  },
  {
    id: 29,
    Name: "Fiona Green",
    Position: "Chief Operating Officer (COO)",
    Office: "San Francisco",
    Age: 48,
    StartDate: "2010-03-11",
    Salary: "850000",
  },
  {
    id: 30,
    Name: "Shou Itou",
    Position: "Regional Marketing",
    Office: "Tokyo",
    Age: 20,
    StartDate: "2011-08-14",
    Salary: "163000",
  },
  {
    id: 31,
    Name: "Michelle House",
    Position: "Integration Specialist",
    Office: "Sydney",
    Age: 37,
    StartDate: "2011-06-02",
    Salary: "95400",
  },
  {
    id: 32,
    Name: "Suki Burks",
    Position: "Developer",
    Office: "London",
    Age: 53,
    StartDate: "2009-10-22",
    Salary: "114500",
  },
  {
    id: 33,
    Name: "Prescott Bartlett",
    Position: "Technical Author",
    Office: "London",
    Age: 27,
    StartDate: "2011-05-07",
    Salary: "145000",
  },
  {
    id: 34,
    Name: "Gavin Cortez",
    Position: "Team Leader",
    Office: "San Francisco",
    Age: 22,
    StartDate: "2008-10-26",
    Salary: "235500",
  },
  {
    id: 35,
    Name: "Martena Mccray",
    Position: "Post-Sales support",
    Office: "Edinburgh",
    Age: 46,
    StartDate: "2011-03-09",
    Salary: "324050",
  },
  {
    id: 36,
    Name: "Unity Butler",
    Position: "Marketing Designer",
    Office: "San Francisco",
    Age: 47,
    StartDate: "2009-12-09",
    Salary: "85675",
  },
  {
    id: 37,
    Name: "Howard Hatfield",
    Position: "Office Manager",
    Office: "San Francisco",
    Age: 51,
    StartDate: "2008-12-16",
    Salary: "164500",
  },
  {
    id: 38,
    Name: "Hope Fuentes",
    Position: "Secretary",
    Office: "San Francisco",
    Age: 41,
    StartDate: "2010-02-12",
    Salary: "109850",
  },
  {
    id: 39,
    Name: "Vivian Harrell",
    Position: "Financial Controller",
    Office: "San Francisco",
    Age: 62,
    StartDate: "2009-02-14",
    Salary: "452500",
  },
  {
    id: 40,
    Name: "Timothy Mooney",
    Position: "Office Manager",
    Office: "London",
    Age: 37,
    StartDate: "2008-12-11",
    Salary: "136200",
  },
  {
    id: 41,
    Name: "Jackson Bradshaw",
    Position: "Director",
    Office: "New York",
    Age: 65,
    StartDate: "2008-09-26",
    Salary: "645750",
  },
  {
    id: 42,
    Name: "Olivia Liang",
    Position: "Support Engineer",
    Office: "Singapore",
    Age: 64,
    StartDate: "2011-02-03",
    Salary: "234500",
  },
  {
    id: 43,
    Name: "Bruno Nash",
    Position: "Software Engineer",
    Office: "London",
    Age: 38,
    StartDate: "2011-05-03",
    Salary: "163500",
  },
  {
    id: 44,
    Name: "Sakura Yamamoto",
    Position: "Support Engineer",
    Office: "Tokyo",
    Age: 37,
    StartDate: "2009-08-19",
    Salary: "139575",
  },
  {
    id: 45,
    Name: "Thor Walton",
    Position: "Developer",
    Office: "New York",
    Age: 61,
    StartDate: "2013-08-11",
    Salary: "98540",
  },
  {
    id: 46,
    Name: "Finn Camacho",
    Position: "Support Engineer",
    Office: "San Francisco",
    Age: 47,
    StartDate: "2009-07-07",
    Salary: "87500",
  },
  {
    id: 47,
    Name: "Serge Baldwin",
    Position: "Data Coordinator",
    Office: "Singapore",
    Age: 64,
    StartDate: "2012-04-09",
    Salary: "138575",
  },
  {
    id: 48,
    Name: "Zenaida Frank",
    Position: "Software Engineer",
    Office: "New York",
    Age: 63,
    StartDate: "2010-01-04",
    Salary: "125250",
  },
  {
    id: 49,
    Name: "Zorita Serrano",
    Position: "Software Engineer",
    Office: "San Francisco",
    Age: 56,
    StartDate: "2012-06-01",
    Salary: "115000",
  },
  {
    id: 50,
    Name: "Jennifer Acosta",
    Position: "Junior Javascript Developer",
    Office: "Edinburgh",
    Age: 43,
    StartDate: "2013-02-01",
    Salary: "75650",
  },
  {
    id: 51,
    Name: "Cara Stevens",
    Position: "Sales Assistant",
    Office: "New York",
    Age: 46,
    StartDate: "2011-12-06",
    Salary: "145600",
  },
  {
    id: 52,
    Name: "Hermione Butler",
    Position: "Regional Director",
    Office: "London",
    Age: 47,
    StartDate: "2011-03-21",
    Salary: "356250",
  },
  {
    id: 53,
    Name: "Lael Greer",
    Position: "Systems Administrator",
    Office: "London",
    Age: 21,
    StartDate: "2009-02-27",
    Salary: "103500",
  },
  {
    id: 54,
    Name: "Jonas Alexander",
    Position: "Developer",
    Office: "San Francisco",
    Age: 30,
    StartDate: "2010-07-14",
    Salary: "86500",
  },
  {
    id: 55,
    Name: "Shad Decker",
    Position: "Regional Director",
    Office: "Edinburgh",
    Age: 51,
    StartDate: "2008-11-13",
    Salary: "183000",
  },
  {
    id: 56,
    Name: "Michael Bruce",
    Position: "Javascript Developer",
    Office: "Singapore",
    Age: 29,
    StartDate: "2011-06-27",
    Salary: "183000",
  },
  {
    id: 57,
    Name: "Donna Snider",
    Position: "Customer Support",
    Office: "New York",
    Age: 27,
    StartDate: "2011-01-25",
    Salary: "112000",
  },
];

const Template: StoryFn<TablePaginationProps> = (
  args: TablePaginationProps
) => <TablePagination {...args} />;

export const Default: StoryFn<TablePaginationProps> = Template.bind({});
Default.args = {
  dataSet: tableData,
};
